/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Denis
 */
public class CursuriProfPanel extends javax.swing.JPanel {

    /**
     * Creates new form CursuriProfPanel
     */
    
    public ArrayList<String> cursuri;
    public DefaultListModel listaCursuriProfModel;
    
    public CursuriProfPanel(ActionListener BackToHomePanelListener, ListSelectionListener CursuriSelectionListener, ActionListener SalvareModificariListener) {
        initComponents();
        listaCursuriProfModel = new DefaultListModel();
        buttonInapoi.addActionListener(BackToHomePanelListener);
        listaCursuri.setModel(listaCursuriProfModel);
        listaCursuri.addListSelectionListener(CursuriSelectionListener);
        buttonSalvare.addActionListener(SalvareModificariListener);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void updateListaCursuriProf(ArrayList<String> data){
        listaCursuriProfModel.removeAllElements();
        cursuri = data;

        for (int i = 0; i < cursuri.size(); i++) {
            listaCursuriProfModel.addElement(cursuri.get(i));
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaCursuri = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldPondereCurs = new javax.swing.JTextField();
        buttonSalvare = new javax.swing.JButton();
        buttonInapoi = new javax.swing.JButton();
        fieldPondereSeminar = new javax.swing.JTextField();
        fieldPondereLab = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 148, 96));

        jScrollPane1.setViewportView(listaCursuri);

        jLabel1.setForeground(new java.awt.Color(66, 71, 72));
        jLabel1.setText("Cursurile mele");

        jLabel2.setForeground(new java.awt.Color(66, 71, 72));
        jLabel2.setText("Pondere Curs");

        jLabel3.setForeground(new java.awt.Color(66, 71, 72));
        jLabel3.setText("Pondere Laborator");

        jLabel4.setForeground(new java.awt.Color(66, 71, 72));
        jLabel4.setText("Pondere Seminar");

        fieldPondereCurs.setBackground(new java.awt.Color(66, 71, 72));
        fieldPondereCurs.setForeground(new java.awt.Color(255, 255, 255));
        fieldPondereCurs.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldPondereCurs.setText("Selectati un curs");
        fieldPondereCurs.setBorder(null);
        fieldPondereCurs.setMinimumSize(new java.awt.Dimension(200, 200));

        buttonSalvare.setBackground(new java.awt.Color(66, 71, 72));
        buttonSalvare.setForeground(new java.awt.Color(255, 255, 255));
        buttonSalvare.setText("Salveaza modificari");
        buttonSalvare.setToolTipText("");

        buttonInapoi.setBackground(new java.awt.Color(66, 71, 72));
        buttonInapoi.setForeground(new java.awt.Color(255, 255, 255));
        buttonInapoi.setText("Inapoi");

        fieldPondereSeminar.setBackground(new java.awt.Color(66, 71, 72));
        fieldPondereSeminar.setForeground(new java.awt.Color(255, 255, 255));
        fieldPondereSeminar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldPondereSeminar.setText("Selectati un curs");
        fieldPondereSeminar.setBorder(null);
        fieldPondereSeminar.setMinimumSize(new java.awt.Dimension(200, 200));

        fieldPondereLab.setBackground(new java.awt.Color(66, 71, 72));
        fieldPondereLab.setForeground(new java.awt.Color(255, 255, 255));
        fieldPondereLab.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldPondereLab.setText("Selectati un curs");
        fieldPondereLab.setBorder(null);
        fieldPondereLab.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(buttonInapoi, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(errorLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSalvare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(fieldPondereCurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31)
                                .addComponent(fieldPondereSeminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(fieldPondereLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldPondereCurs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPondereLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPondereSeminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInapoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSalvare, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonInapoi;
    public javax.swing.JButton buttonSalvare;
    public javax.swing.JLabel errorLabel;
    public javax.swing.JTextField fieldPondereCurs;
    public javax.swing.JTextField fieldPondereLab;
    public javax.swing.JTextField fieldPondereSeminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList<String> listaCursuri;
    // End of variables declaration//GEN-END:variables
}
