/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import BDProjectv7.StudentViewController;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Denis
 */
public class GrupStudiuPanel extends javax.swing.JPanel {

    /**
     * Creates new form GrupStudiuPanel
     */
    
    
    public DefaultListModel grupeListModel;
    public DefaultListModel invitatiiListModel;
    
    public ArrayList<Integer> grupe;
    public ArrayList<Integer> invitatii;
    
    public GrupStudiuPanel(ActionListener BackToHomePanelListener, ActionListener CreareGrupaNouaListener, ActionListener InscriereGrupaListener, 
            ActionListener VizualizareGrupaListener, ListSelectionListener GrupeSelectionListener, ActionListener AcceptInviteListener){
    initComponents();
    grupeListModel = new DefaultListModel();
    invitatiiListModel = new DefaultListModel();
    
    
    buttonIntoarcere.addActionListener(BackToHomePanelListener);
    buttonCreareGrupaNoua.addActionListener(CreareGrupaNouaListener);
    buttonInscriereGrupa.addActionListener(InscriereGrupaListener);
    buttonVizGrupa.addActionListener(VizualizareGrupaListener);
    buttonAcceptInvitation.addActionListener(AcceptInviteListener);
    listaGrupe.setModel(grupeListModel);
    listaGrupe.getSelectionModel().addListSelectionListener(GrupeSelectionListener);
    invitatiiGrupaList.setModel(invitatiiListModel);
    }
    
    
    
    public void updateListaGrupe(ArrayList<Integer> data, ArrayList<String> numeCursuri){
        if(data != null)
        {
            grupeListModel.removeAllElements();
            grupe = data;

            for (int i = 0; i < grupe.size(); i++) {
                grupeListModel.addElement("Grupa " + Integer.toString(grupe.get(i))+ " - " + numeCursuri.get(i));
            }
        }
    }
    
    public void updateListaInvitatii(){
        if(invitatii != null)   
        {
            invitatiiListModel.removeAllElements();
            for(int i = 0; i < invitatii.size(); i++)
                invitatiiListModel.addElement("Grupa " + Integer.toString(invitatii.get(i)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaGrupe = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        buttonVizGrupa = new javax.swing.JButton();
        buttonCreareGrupaNoua = new javax.swing.JButton();
        buttonInscriereGrupa = new javax.swing.JButton();
        buttonIntoarcere = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        invitatiiGrupaList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        buttonAcceptInvitation = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 148, 96));

        listaGrupe.setForeground(new java.awt.Color(66, 71, 72));
        listaGrupe.setSelectionBackground(new java.awt.Color(66, 71, 72));
        listaGrupe.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listaGrupe);

        jLabel1.setBackground(new java.awt.Color(66, 71, 72));
        jLabel1.setForeground(new java.awt.Color(66, 71, 72));
        jLabel1.setText("Grupele mele");

        buttonVizGrupa.setBackground(new java.awt.Color(66, 71, 72));
        buttonVizGrupa.setForeground(new java.awt.Color(255, 255, 255));
        buttonVizGrupa.setText("Vizualizare grupa");
        buttonVizGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVizGrupaActionPerformed(evt);
            }
        });

        buttonCreareGrupaNoua.setBackground(new java.awt.Color(66, 71, 72));
        buttonCreareGrupaNoua.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreareGrupaNoua.setText("Creare grupa");
        buttonCreareGrupaNoua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreareGrupaNouaActionPerformed(evt);
            }
        });

        buttonInscriereGrupa.setBackground(new java.awt.Color(66, 71, 72));
        buttonInscriereGrupa.setForeground(new java.awt.Color(255, 255, 255));
        buttonInscriereGrupa.setText("Inscriere grupa");
        buttonInscriereGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInscriereGrupaActionPerformed(evt);
            }
        });

        buttonIntoarcere.setBackground(new java.awt.Color(66, 71, 72));
        buttonIntoarcere.setForeground(new java.awt.Color(255, 255, 255));
        buttonIntoarcere.setText("Inapoi");

        invitatiiGrupaList.setForeground(new java.awt.Color(66, 71, 72));
        invitatiiGrupaList.setSelectionBackground(new java.awt.Color(66, 71, 72));
        invitatiiGrupaList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(invitatiiGrupaList);

        jLabel2.setForeground(new java.awt.Color(66, 71, 72));
        jLabel2.setText("Invitatii grupe");

        buttonAcceptInvitation.setBackground(new java.awt.Color(66, 71, 72));
        buttonAcceptInvitation.setForeground(new java.awt.Color(255, 255, 255));
        buttonAcceptInvitation.setText("Accepta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonInscriereGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonVizGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCreareGrupaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(buttonAcceptInvitation, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(buttonIntoarcere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonVizGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInscriereGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCreareGrupaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAcceptInvitation, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonIntoarcere, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVizGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVizGrupaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVizGrupaActionPerformed

    private void buttonCreareGrupaNouaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreareGrupaNouaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCreareGrupaNouaActionPerformed

    private void buttonInscriereGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInscriereGrupaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInscriereGrupaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonAcceptInvitation;
    public javax.swing.JButton buttonCreareGrupaNoua;
    public javax.swing.JButton buttonInscriereGrupa;
    public javax.swing.JButton buttonIntoarcere;
    public javax.swing.JButton buttonVizGrupa;
    public javax.swing.JList<String> invitatiiGrupaList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JList<String> listaGrupe;
    // End of variables declaration//GEN-END:variables

}
