package UIPackage;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;

public class InscriereCursPanel extends javax.swing.JPanel {

    public ArrayList<ArrayList<String>> cursuriCurenteData; // [i][0] - nume curs, [i][1] - descriere curs, [i][2] - nume prof, [i][3] prenume prof
    public ArrayList<String> cursuriPosibileData;
    
    public DefaultListModel cursuriCurenteListModel;
    public DefaultListModel cursuriPosibileListModel;

    public InscriereCursPanel(ActionListener backButtonListener, ListSelectionListener cursuriCurenteSelectionListener, ActionListener inscriereCursListener, ActionListener parasireCursButtonListener) {
        initComponents();
        backButton.addActionListener(backButtonListener);
        inscriereCursButton.addActionListener(inscriereCursListener);
        parasireCursButton.addActionListener(parasireCursButtonListener);
        
        cursuriCurenteListModel = new DefaultListModel();
        cursuriCurenteList.setModel(cursuriCurenteListModel);
        cursuriCurenteList.getSelectionModel().addListSelectionListener(cursuriCurenteSelectionListener);
        
        cursuriPosibileListModel = new DefaultListModel();
        cursuriPosibileList.setModel(cursuriPosibileListModel);  
        
    }

    public void updateCursuriCurenteData(ArrayList<ArrayList<String>> data){
        cursuriCurenteData = data;
        cursuriCurenteListModel.removeAllElements();    
        for (int i = 0; i < cursuriCurenteData.size(); i++) {
            // index 0 - nume curs, 1 - descriere curs, 2 - nume prof, 3 - prenume prof
            cursuriCurenteListModel.addElement(cursuriCurenteData.get(i).get(0)); // nume curs
        }  
    }
    public void updateCursuriPosibileData(ArrayList<String> data){
        cursuriPosibileData = data;
        cursuriPosibileListModel.removeAllElements();
        for (int i = 0; i < cursuriPosibileData.size(); i++) 
            cursuriPosibileListModel.addElement(cursuriPosibileData.get(i)); // nume curs
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        inscriereCursButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cursuriCurenteList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cursuriPosibileList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriereTextBox = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        profesorCursField = new javax.swing.JTextField();
        parasireCursButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(255, 148, 96));

        backButton.setBackground(new java.awt.Color(66, 71, 72));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");

        inscriereCursButton.setBackground(new java.awt.Color(66, 71, 72));
        inscriereCursButton.setForeground(new java.awt.Color(255, 255, 255));
        inscriereCursButton.setText("Inscrie-te");

        cursuriCurenteList.setSelectionBackground(new java.awt.Color(66, 71, 72));
        cursuriCurenteList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(cursuriCurenteList);

        jLabel1.setForeground(new java.awt.Color(66, 71, 72));
        jLabel1.setText("Cursuri la care esti inscris:");

        cursuriPosibileList.setSelectionBackground(new java.awt.Color(66, 71, 72));
        cursuriPosibileList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(cursuriPosibileList);

        jLabel2.setForeground(new java.awt.Color(66, 71, 72));
        jLabel2.setText("Cursuri la care te poti inscrie:");

        jLabel3.setForeground(new java.awt.Color(66, 71, 72));
        jLabel3.setText("Descriere:");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        descriereTextBox.setColumns(20);
        descriereTextBox.setLineWrap(true);
        descriereTextBox.setRows(5);
        jScrollPane3.setViewportView(descriereTextBox);

        jLabel4.setForeground(new java.awt.Color(66, 71, 72));
        jLabel4.setText("Profesor:");

        parasireCursButton.setBackground(new java.awt.Color(66, 71, 72));
        parasireCursButton.setForeground(new java.awt.Color(255, 255, 255));
        parasireCursButton.setText("Paraseste curs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(inscriereCursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesorCursField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parasireCursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profesorCursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parasireCursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscriereCursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButton;
    public javax.swing.JList<String> cursuriCurenteList;
    public javax.swing.JList<String> cursuriPosibileList;
    public javax.swing.JTextArea descriereTextBox;
    public javax.swing.JButton inscriereCursButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JButton parasireCursButton;
    public javax.swing.JTextField profesorCursField;
    // End of variables declaration//GEN-END:variables
}
