package UIPackage;
        
import java.awt.event.ActionListener;

        
public class ProfesorHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public ProfesorHomePanel(ActionListener logoutButtonListener, ActionListener vizDateProfesorListener,
            ActionListener vizInvitatiiListener, ActionListener activitatiProfesorListener, ActionListener vizCatalogListener, ActionListener programareActivitatiListener, ActionListener vizCursuriListener) {
        initComponents();
        buttonLogOut.addActionListener(logoutButtonListener);
        buttonVizDatePers.addActionListener(vizDateProfesorListener);
        buttonVizualizareInvitatii.addActionListener(vizInvitatiiListener);
        buttonVizCatalog.addActionListener(vizCatalogListener);
        buttonVizActiv.addActionListener(activitatiProfesorListener);
        buttonVizCursuri.addActionListener(vizCursuriListener);
        buttonProgramareActiv.addActionListener(programareActivitatiListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVizDatePers = new javax.swing.JButton();
        buttonVizActiv = new javax.swing.JButton();
        buttonProgramareActiv = new javax.swing.JButton();
        buttonLogOut = new javax.swing.JButton();
        buttonVizCursuri = new javax.swing.JButton();
        buttonVizCatalog = new javax.swing.JButton();
        buttonVizualizareInvitatii = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 148, 96));
        setPreferredSize(new java.awt.Dimension(682, 425));

        buttonVizDatePers.setBackground(new java.awt.Color(66, 71, 72));
        buttonVizDatePers.setForeground(new java.awt.Color(255, 255, 255));
        buttonVizDatePers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/006-man.png"))); // NOI18N
        buttonVizDatePers.setText("Vizualizare date personale");
        buttonVizDatePers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonVizDatePers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonVizActiv.setBackground(new java.awt.Color(66, 71, 72));
        buttonVizActiv.setForeground(new java.awt.Color(255, 255, 255));
        buttonVizActiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/005-calendar.png"))); // NOI18N
        buttonVizActiv.setText("Activitatile mele");
        buttonVizActiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonVizActiv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonProgramareActiv.setBackground(new java.awt.Color(66, 71, 72));
        buttonProgramareActiv.setForeground(new java.awt.Color(255, 255, 255));
        buttonProgramareActiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/007-computer.png"))); // NOI18N
        buttonProgramareActiv.setText("Programare activitati");
        buttonProgramareActiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonProgramareActiv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonLogOut.setBackground(new java.awt.Color(66, 71, 72));
        buttonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogOut.setText("Log out");

        buttonVizCursuri.setBackground(new java.awt.Color(66, 71, 72));
        buttonVizCursuri.setForeground(new java.awt.Color(255, 255, 255));
        buttonVizCursuri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002-library.png"))); // NOI18N
        buttonVizCursuri.setText("Cursuri");
        buttonVizCursuri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonVizCursuri.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonVizCatalog.setBackground(new java.awt.Color(66, 71, 72));
        buttonVizCatalog.setForeground(new java.awt.Color(255, 255, 255));
        buttonVizCatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/003-presentation.png"))); // NOI18N
        buttonVizCatalog.setText("Catalog");
        buttonVizCatalog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonVizCatalog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonVizualizareInvitatii.setBackground(new java.awt.Color(66, 71, 72));
        buttonVizualizareInvitatii.setForeground(new java.awt.Color(255, 255, 255));
        buttonVizualizareInvitatii.setIcon(new javax.swing.ImageIcon(getClass().getResource("/009-chat.png"))); // NOI18N
        buttonVizualizareInvitatii.setText("Vizualizare Invitatii");
        buttonVizualizareInvitatii.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonVizualizareInvitatii.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonVizActiv, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonProgramareActiv, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonVizualizareInvitatii, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonVizDatePers, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonVizCursuri, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonVizCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonVizCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonVizDatePers, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonVizActiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonProgramareActiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonVizualizareInvitatii, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonVizCursuri, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JButton buttonProgramareActiv;
    public javax.swing.JButton buttonVizActiv;
    public javax.swing.JButton buttonVizCatalog;
    public javax.swing.JButton buttonVizCursuri;
    public javax.swing.JButton buttonVizDatePers;
    public javax.swing.JButton buttonVizualizareInvitatii;
    // End of variables declaration//GEN-END:variables
}
