/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;

/**
 *
 * @author Denis
 */
public class ProgramareActivitateProfesorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgramareActivitateProfesor
    
     */
    public ArrayList<String> cursuri;
    public DefaultListModel listaCursuriProfModel;
    public Object errorLabel;
    
    public ProgramareActivitateProfesorPanel(ActionListener BackToHomePanelListener,
            ActionListener ProgramareCursListener, ActionListener ProgramareLaboratorListener, 
            ActionListener ProgramareSeminarListener, ActionListener ProgramareExamenListener) {
        initComponents();
        buttonIntoarcere.addActionListener(BackToHomePanelListener);
        listaCursuriProfModel = new DefaultListModel();
        listaCursuriProfesor.setModel(listaCursuriProfModel);
        buttonProgramareCurs.addActionListener(ProgramareCursListener);
        buttonProgramareLab.addActionListener(ProgramareLaboratorListener);
        buttonProgramareSeminar.addActionListener(ProgramareSeminarListener);
        buttonProgramareExamen.addActionListener(ProgramareExamenListener);
    }
    
    public String tipExamen(){
        if (buttonColocviu.isSelected())
            return "colocviu";
        else return "examen final";
    }
    
    public javax.swing.JTextField[] getAllFieldsCurs(){
        JTextField[] fields = new JTextField[6];
        fields[0] = fieldDataIncepere;
        fields[1] = fieldDataFinalizare;
        fields[2] = fieldZiua;
        fields[3] = fieldOra;
        fields[4] = fieldDurata;
        fields[5] = fieldLocuriMax;
        return fields;
    }
    
    public javax.swing.JTextField[] getAllFieldsLab(){
        JTextField[] fields = new JTextField[6];
        fields[0] = fieldDataIncepereLab;
        fields[1] = fieldDataFinalizareLab;
        fields[2] = fieldZiuaLab;
        fields[3] = fieldOraLab;
        fields[4] = fieldDurataLab;
        fields[5] = fieldLocuriMaxLab;
        return fields;
    }
    
    public javax.swing.JTextField[] getAllFieldsSeminar(){
        JTextField[] fields = new JTextField[6];
        fields[0] = fieldDataIncepereSem;
        fields[1] = fieldDataFinalizareSem;
        fields[2] = fieldZiuaSem;
        fields[3] = fieldOraSem;
        fields[4] = fieldDurataSem;
        fields[5] = fieldLocuriMaxSem;
        return fields;
    }
    
     public javax.swing.JTextField[] getAllFieldsExamen(){
        JTextField[] fields = new JTextField[6];
        fields[0] = fieldDataExamen;
        fields[1] = fieldDataExamen;
        fields[2] = fieldZiuaExamen;
        fields[3] = fieldOraExamen;
        fields[4] = fieldDurataExamen;
        fields[5] = fieldLocuriMaximeExamen;
        return fields;
    }
    

    public void updateListaCursuriProf(ArrayList<String> data){
        listaCursuriProfModel.removeAllElements();
        cursuri = data;

        for (int i = 0; i < cursuri.size(); i++) {
            listaCursuriProfModel.addElement(cursuri.get(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCursuriProfesor = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        panelProgCurs = new javax.swing.JPanel();
        fieldDataIncepere = new javax.swing.JTextField();
        fieldDataFinalizare = new javax.swing.JTextField();
        fieldZiua = new javax.swing.JTextField();
        fieldOra = new javax.swing.JTextField();
        fieldDurata = new javax.swing.JTextField();
        fieldLocuriMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelProgLab = new javax.swing.JPanel();
        fieldDataIncepereLab = new javax.swing.JTextField();
        fieldDataFinalizareLab = new javax.swing.JTextField();
        fieldZiuaLab = new javax.swing.JTextField();
        fieldOraLab = new javax.swing.JTextField();
        fieldDurataLab = new javax.swing.JTextField();
        fieldLocuriMaxLab = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panelProgSeminar = new javax.swing.JPanel();
        fieldDataIncepereSem = new javax.swing.JTextField();
        fieldDataFinalizareSem = new javax.swing.JTextField();
        fieldZiuaSem = new javax.swing.JTextField();
        fieldOraSem = new javax.swing.JTextField();
        fieldDurataSem = new javax.swing.JTextField();
        fieldLocuriMaxSem = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        buttonIntoarcere = new javax.swing.JButton();
        buttonProgramareLab = new javax.swing.JButton();
        buttonProgramareSeminar = new javax.swing.JButton();
        buttonProgramareCurs = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonExamen = new javax.swing.JRadioButton();
        buttonColocviu = new javax.swing.JRadioButton();
        jLabel47 = new javax.swing.JLabel();
        fieldDataExamen = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        fieldZiuaExamen = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        fieldOraExamen = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        fieldDurataExamen = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        fieldLocuriMaximeExamen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buttonProgramareExamen = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 148, 96));

        listaCursuriProfesor.setSelectionBackground(new java.awt.Color(66, 71, 72));
        listaCursuriProfesor.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listaCursuriProfesor);

        jLabel1.setForeground(new java.awt.Color(66, 71, 72));
        jLabel1.setText("Cursurile mele");

        panelProgCurs.setBackground(new java.awt.Color(255, 148, 96));

        fieldDataIncepere.setBackground(new java.awt.Color(66, 71, 72));
        fieldDataIncepere.setForeground(new java.awt.Color(255, 255, 255));
        fieldDataIncepere.setText("YYYY-MM-DD");
        fieldDataIncepere.setBorder(null);
        fieldDataIncepere.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldDataIncepere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDataIncepereActionPerformed(evt);
            }
        });

        fieldDataFinalizare.setBackground(new java.awt.Color(66, 71, 72));
        fieldDataFinalizare.setForeground(new java.awt.Color(255, 255, 255));
        fieldDataFinalizare.setText("YYYY-MM-DD");
        fieldDataFinalizare.setBorder(null);

        fieldZiua.setBackground(new java.awt.Color(66, 71, 72));
        fieldZiua.setForeground(new java.awt.Color(255, 255, 255));
        fieldZiua.setBorder(null);

        fieldOra.setBackground(new java.awt.Color(66, 71, 72));
        fieldOra.setForeground(new java.awt.Color(255, 255, 255));
        fieldOra.setText("HH:MM:SS");
        fieldOra.setBorder(null);

        fieldDurata.setBackground(new java.awt.Color(66, 71, 72));
        fieldDurata.setForeground(new java.awt.Color(255, 255, 255));
        fieldDurata.setText("in ore");
        fieldDurata.setBorder(null);

        fieldLocuriMax.setBackground(new java.awt.Color(66, 71, 72));
        fieldLocuriMax.setForeground(new java.awt.Color(255, 255, 255));
        fieldLocuriMax.setBorder(null);

        jLabel5.setForeground(new java.awt.Color(66, 71, 72));
        jLabel5.setText("Data incepere");

        jLabel6.setForeground(new java.awt.Color(66, 71, 72));
        jLabel6.setText("Data finalizare");

        jLabel7.setForeground(new java.awt.Color(66, 71, 72));
        jLabel7.setText("Ziua");

        jLabel8.setForeground(new java.awt.Color(66, 71, 72));
        jLabel8.setText("Ora");

        jLabel9.setForeground(new java.awt.Color(66, 71, 72));
        jLabel9.setText("Durata");

        jLabel10.setForeground(new java.awt.Color(66, 71, 72));
        jLabel10.setText("Locuri maxime");

        javax.swing.GroupLayout panelProgCursLayout = new javax.swing.GroupLayout(panelProgCurs);
        panelProgCurs.setLayout(panelProgCursLayout);
        panelProgCursLayout.setHorizontalGroup(
            panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProgCursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldDataFinalizare)
                    .addComponent(fieldDataIncepere)
                    .addComponent(fieldZiua)
                    .addComponent(fieldOra)
                    .addComponent(fieldDurata)
                    .addComponent(fieldLocuriMax))
                .addContainerGap())
        );
        panelProgCursLayout.setVerticalGroup(
            panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgCursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDataIncepere, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDataFinalizare, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldZiua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldOra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDurata, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLocuriMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25))
        );

        jLabel2.setForeground(new java.awt.Color(66, 71, 72));
        jLabel2.setText("Programare Curs");

        jLabel3.setForeground(new java.awt.Color(66, 71, 72));
        jLabel3.setText("Programare Laborator");

        jLabel4.setForeground(new java.awt.Color(66, 71, 72));
        jLabel4.setText("Programare Seminar");

        panelProgLab.setBackground(new java.awt.Color(255, 148, 96));

        fieldDataIncepereLab.setBackground(new java.awt.Color(66, 71, 72));
        fieldDataIncepereLab.setForeground(new java.awt.Color(255, 255, 255));
        fieldDataIncepereLab.setText("YYYY-MM-DD");
        fieldDataIncepereLab.setBorder(null);

        fieldDataFinalizareLab.setBackground(new java.awt.Color(66, 71, 72));
        fieldDataFinalizareLab.setForeground(new java.awt.Color(255, 255, 255));
        fieldDataFinalizareLab.setText("YYYY-MM-DD");
        fieldDataFinalizareLab.setBorder(null);

        fieldZiuaLab.setBackground(new java.awt.Color(66, 71, 72));
        fieldZiuaLab.setForeground(new java.awt.Color(255, 255, 255));
        fieldZiuaLab.setBorder(null);

        fieldOraLab.setBackground(new java.awt.Color(66, 71, 72));
        fieldOraLab.setForeground(new java.awt.Color(255, 255, 255));
        fieldOraLab.setText("HH:MM:SS");
        fieldOraLab.setBorder(null);

        fieldDurataLab.setBackground(new java.awt.Color(66, 71, 72));
        fieldDurataLab.setForeground(new java.awt.Color(255, 255, 255));
        fieldDurataLab.setText("in ore");
        fieldDurataLab.setBorder(null);

        fieldLocuriMaxLab.setBackground(new java.awt.Color(66, 71, 72));
        fieldLocuriMaxLab.setForeground(new java.awt.Color(255, 255, 255));
        fieldLocuriMaxLab.setBorder(null);

        jLabel23.setForeground(new java.awt.Color(66, 71, 72));
        jLabel23.setText("Data incepere");

        jLabel24.setForeground(new java.awt.Color(66, 71, 72));
        jLabel24.setText("Data finalizare");

        jLabel25.setForeground(new java.awt.Color(66, 71, 72));
        jLabel25.setText("Ziua");

        jLabel26.setForeground(new java.awt.Color(66, 71, 72));
        jLabel26.setText("Ora");

        jLabel27.setForeground(new java.awt.Color(66, 71, 72));
        jLabel27.setText("Durata");

        jLabel28.setForeground(new java.awt.Color(66, 71, 72));
        jLabel28.setText("Locuri maxime");

        javax.swing.GroupLayout panelProgLabLayout = new javax.swing.GroupLayout(panelProgLab);
        panelProgLab.setLayout(panelProgLabLayout);
        panelProgLabLayout.setHorizontalGroup(
            panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProgLabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldDataFinalizareLab)
                    .addComponent(fieldDataIncepereLab)
                    .addComponent(fieldZiuaLab)
                    .addComponent(fieldOraLab)
                    .addComponent(fieldDurataLab)
                    .addComponent(fieldLocuriMaxLab))
                .addContainerGap())
        );
        panelProgLabLayout.setVerticalGroup(
            panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgLabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDataIncepereLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDataFinalizareLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldZiuaLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldOraLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDurataLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLocuriMaxLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(25, 25, 25))
        );

        panelProgSeminar.setBackground(new java.awt.Color(255, 148, 96));

        fieldDataIncepereSem.setBackground(new java.awt.Color(66, 71, 72));
        fieldDataIncepereSem.setForeground(new java.awt.Color(255, 255, 255));
        fieldDataIncepereSem.setText("YYYY-MM-DD");
        fieldDataIncepereSem.setBorder(null);

        fieldDataFinalizareSem.setBackground(new java.awt.Color(66, 71, 72));
        fieldDataFinalizareSem.setForeground(new java.awt.Color(255, 255, 255));
        fieldDataFinalizareSem.setText("YYYY-MM-DD");
        fieldDataFinalizareSem.setBorder(null);

        fieldZiuaSem.setBackground(new java.awt.Color(66, 71, 72));
        fieldZiuaSem.setForeground(new java.awt.Color(255, 255, 255));
        fieldZiuaSem.setBorder(null);

        fieldOraSem.setBackground(new java.awt.Color(66, 71, 72));
        fieldOraSem.setForeground(new java.awt.Color(255, 255, 255));
        fieldOraSem.setText("HH:MM:SS");
        fieldOraSem.setBorder(null);

        fieldDurataSem.setBackground(new java.awt.Color(66, 71, 72));
        fieldDurataSem.setForeground(new java.awt.Color(255, 255, 255));
        fieldDurataSem.setText("in ore");
        fieldDurataSem.setBorder(null);

        fieldLocuriMaxSem.setBackground(new java.awt.Color(66, 71, 72));
        fieldLocuriMaxSem.setForeground(new java.awt.Color(255, 255, 255));
        fieldLocuriMaxSem.setBorder(null);

        jLabel41.setForeground(new java.awt.Color(66, 71, 72));
        jLabel41.setText("Data incepere");

        jLabel42.setForeground(new java.awt.Color(66, 71, 72));
        jLabel42.setText("Data finalizare");

        jLabel43.setForeground(new java.awt.Color(66, 71, 72));
        jLabel43.setText("Ziua");

        jLabel44.setForeground(new java.awt.Color(66, 71, 72));
        jLabel44.setText("Ora");

        jLabel45.setForeground(new java.awt.Color(66, 71, 72));
        jLabel45.setText("Durata");

        jLabel46.setForeground(new java.awt.Color(66, 71, 72));
        jLabel46.setText("Locuri maxime");

        javax.swing.GroupLayout panelProgSeminarLayout = new javax.swing.GroupLayout(panelProgSeminar);
        panelProgSeminar.setLayout(panelProgSeminarLayout);
        panelProgSeminarLayout.setHorizontalGroup(
            panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProgSeminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addGap(18, 18, 18)
                .addGroup(panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldDataFinalizareSem)
                    .addComponent(fieldDataIncepereSem)
                    .addComponent(fieldZiuaSem)
                    .addComponent(fieldOraSem)
                    .addComponent(fieldDurataSem)
                    .addComponent(fieldLocuriMaxSem))
                .addContainerGap())
        );
        panelProgSeminarLayout.setVerticalGroup(
            panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgSeminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDataIncepereSem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDataFinalizareSem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldZiuaSem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldOraSem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDurataSem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProgSeminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLocuriMaxSem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addGap(25, 25, 25))
        );

        buttonIntoarcere.setBackground(new java.awt.Color(66, 71, 72));
        buttonIntoarcere.setForeground(new java.awt.Color(255, 255, 255));
        buttonIntoarcere.setLabel("Intoarcere");
        buttonIntoarcere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIntoarcereActionPerformed(evt);
            }
        });

        buttonProgramareLab.setBackground(new java.awt.Color(66, 71, 72));
        buttonProgramareLab.setForeground(new java.awt.Color(255, 255, 255));
        buttonProgramareLab.setText("Programeaza activitatea");

        buttonProgramareSeminar.setBackground(new java.awt.Color(66, 71, 72));
        buttonProgramareSeminar.setForeground(new java.awt.Color(255, 255, 255));
        buttonProgramareSeminar.setText("Programeaza activitatea");

        buttonProgramareCurs.setBackground(new java.awt.Color(66, 71, 72));
        buttonProgramareCurs.setForeground(new java.awt.Color(255, 255, 255));
        buttonProgramareCurs.setText("Programeaza activitatea");

        jLabel11.setForeground(new java.awt.Color(66, 71, 72));
        jLabel11.setText("Pentru a programa o activitate, nu uitati sa selectati cursul din lista afisata in stanga!");

        jPanel1.setBackground(new java.awt.Color(255, 148, 96));

        buttonExamen.setBackground(new java.awt.Color(255, 148, 96));
        buttonGroup1.add(buttonExamen);
        buttonExamen.setForeground(new java.awt.Color(66, 71, 72));
        buttonExamen.setText("Examen final");
        buttonExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExamenActionPerformed(evt);
            }
        });

        buttonColocviu.setBackground(new java.awt.Color(255, 148, 96));
        buttonGroup1.add(buttonColocviu);
        buttonColocviu.setForeground(new java.awt.Color(66, 71, 72));
        buttonColocviu.setText("Colocviu");

        jLabel47.setForeground(new java.awt.Color(66, 71, 72));
        jLabel47.setText("Data ");

        fieldDataExamen.setBackground(new java.awt.Color(66, 71, 72));
        fieldDataExamen.setForeground(new java.awt.Color(255, 255, 255));
        fieldDataExamen.setText("YYYY-MM-DD");
        fieldDataExamen.setBorder(null);

        jLabel48.setForeground(new java.awt.Color(66, 71, 72));
        jLabel48.setText("Ziua");

        fieldZiuaExamen.setBackground(new java.awt.Color(66, 71, 72));
        fieldZiuaExamen.setForeground(new java.awt.Color(255, 255, 255));
        fieldZiuaExamen.setBorder(null);

        jLabel49.setForeground(new java.awt.Color(66, 71, 72));
        jLabel49.setText("Ora");

        fieldOraExamen.setBackground(new java.awt.Color(66, 71, 72));
        fieldOraExamen.setForeground(new java.awt.Color(255, 255, 255));
        fieldOraExamen.setText("HH:MM:SS");
        fieldOraExamen.setBorder(null);

        jLabel50.setForeground(new java.awt.Color(66, 71, 72));
        jLabel50.setText("Durata");

        fieldDurataExamen.setBackground(new java.awt.Color(66, 71, 72));
        fieldDurataExamen.setForeground(new java.awt.Color(255, 255, 255));
        fieldDurataExamen.setText("in ore");
        fieldDurataExamen.setBorder(null);

        jLabel51.setForeground(new java.awt.Color(66, 71, 72));
        jLabel51.setText("Locuri maxime");

        fieldLocuriMaximeExamen.setBackground(new java.awt.Color(66, 71, 72));
        fieldLocuriMaximeExamen.setForeground(new java.awt.Color(255, 255, 255));
        fieldLocuriMaximeExamen.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonColocviu)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExamen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldDataExamen)
                            .addComponent(fieldZiuaExamen)
                            .addComponent(fieldOraExamen)
                            .addComponent(fieldDurataExamen)
                            .addComponent(fieldLocuriMaximeExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonColocviu)
                    .addComponent(buttonExamen))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDataExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldZiuaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldOraExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDurataExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLocuriMaximeExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel12.setForeground(new java.awt.Color(66, 71, 72));
        jLabel12.setText("Programare Examen");

        buttonProgramareExamen.setBackground(new java.awt.Color(66, 71, 72));
        buttonProgramareExamen.setForeground(new java.awt.Color(255, 255, 255));
        buttonProgramareExamen.setText("Programeaza activitatea");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelProgCurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(buttonProgramareCurs, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(panelProgLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonProgramareLab, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelProgSeminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(buttonProgramareSeminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(buttonProgramareExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel11)))
                    .addComponent(buttonIntoarcere, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelProgCurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(panelProgLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelProgSeminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonProgramareLab, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProgramareSeminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProgramareCurs, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProgramareExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonIntoarcere, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIntoarcereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIntoarcereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonIntoarcereActionPerformed

    private void fieldDataIncepereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDataIncepereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDataIncepereActionPerformed

    private void buttonExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExamenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton buttonColocviu;
    public javax.swing.JRadioButton buttonExamen;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton buttonIntoarcere;
    public javax.swing.JButton buttonProgramareCurs;
    public javax.swing.JButton buttonProgramareExamen;
    public javax.swing.JButton buttonProgramareLab;
    public javax.swing.JButton buttonProgramareSeminar;
    public javax.swing.JTextField fieldDataExamen;
    public javax.swing.JTextField fieldDataFinalizare;
    public javax.swing.JTextField fieldDataFinalizareLab;
    public javax.swing.JTextField fieldDataFinalizareSem;
    public javax.swing.JTextField fieldDataIncepere;
    public javax.swing.JTextField fieldDataIncepereLab;
    public javax.swing.JTextField fieldDataIncepereSem;
    public javax.swing.JTextField fieldDurata;
    public javax.swing.JTextField fieldDurataExamen;
    public javax.swing.JTextField fieldDurataLab;
    public javax.swing.JTextField fieldDurataSem;
    public javax.swing.JTextField fieldLocuriMax;
    public javax.swing.JTextField fieldLocuriMaxLab;
    public javax.swing.JTextField fieldLocuriMaxSem;
    public javax.swing.JTextField fieldLocuriMaximeExamen;
    public javax.swing.JTextField fieldOra;
    public javax.swing.JTextField fieldOraExamen;
    public javax.swing.JTextField fieldOraLab;
    public javax.swing.JTextField fieldOraSem;
    public javax.swing.JTextField fieldZiua;
    public javax.swing.JTextField fieldZiuaExamen;
    public javax.swing.JTextField fieldZiuaLab;
    public javax.swing.JTextField fieldZiuaSem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList<String> listaCursuriProfesor;
    public javax.swing.JPanel panelProgCurs;
    public javax.swing.JPanel panelProgLab;
    public javax.swing.JPanel panelProgSeminar;
    // End of variables declaration//GEN-END:variables
}
