/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author Denis
 */
public class ProgramareActivitateGrupaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgramareActivitateGrupaPanel
     */
    public ArrayList<ArrayList<String>> sugestiiProfesori;
    
    public ProgramareActivitateGrupaPanel(ActionListener BackToVizGrupaListener, ActionListener ProgramareActivitateInsertListener) {
        initComponents();
        buttonIntoarcereVizGrupa.addActionListener(BackToVizGrupaListener);
        buttonInsertActGrupa.addActionListener(ProgramareActivitateInsertListener);
    }
    
    public void updateSugestiiProfesor(){
        selectareProfComboBox.removeAllItems();
        for(int i = 0; i < sugestiiProfesori.size(); i++){
            String numeprenume = sugestiiProfesori.get(i).get(1) + " " + sugestiiProfesori.get(i).get(2);
            selectareProfComboBox.addItem(numeprenume);
        }
    }
    
    public javax.swing.JTextField[] getAllFields(){
        JTextField[] fields = new JTextField[9];
        fields[0] = dataIncepereField;
        fields[1] = dataFinalizareField;
        fields[2] = ziActivitateField;
        fields[3] = oraField;
        fields[4] = durataField;
        fields[5] = tipActivitateField;
        fields[6] = partMinimField;
        fields[7] = partMaximField;
        fields[8] = timpExpiareField;
        return fields;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tipActivitateField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dataIncepereField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        oraField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        partMinimField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        durataField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dataFinalizareField = new javax.swing.JTextField();
        ziActivitateField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        partMaximField = new javax.swing.JTextField();
        buttonInsertActGrupa = new javax.swing.JButton();
        buttonIntoarcereVizGrupa = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        timpExpiareField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        selectareProfComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        solicitProfCheckBox = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 148, 96));

        jLabel1.setForeground(new java.awt.Color(66, 71, 72));
        jLabel1.setText("Nume activitate");

        tipActivitateField.setBackground(new java.awt.Color(66, 71, 72));
        tipActivitateField.setForeground(new java.awt.Color(255, 255, 255));
        tipActivitateField.setBorder(null);
        tipActivitateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipActivitateFieldActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(66, 71, 72));
        jLabel2.setText("Data incepere");

        dataIncepereField.setBackground(new java.awt.Color(66, 71, 72));
        dataIncepereField.setForeground(new java.awt.Color(255, 255, 255));
        dataIncepereField.setBorder(null);

        jLabel3.setForeground(new java.awt.Color(66, 71, 72));
        jLabel3.setText("Ora");

        oraField.setBackground(new java.awt.Color(66, 71, 72));
        oraField.setForeground(new java.awt.Color(255, 255, 255));
        oraField.setBorder(null);

        jLabel4.setForeground(new java.awt.Color(66, 71, 72));
        jLabel4.setText("Numar minim de participanti");

        partMinimField.setBackground(new java.awt.Color(66, 71, 72));
        partMinimField.setForeground(new java.awt.Color(255, 255, 255));
        partMinimField.setBorder(null);

        jLabel5.setForeground(new java.awt.Color(66, 71, 72));
        jLabel5.setText("Durata");

        durataField.setBackground(new java.awt.Color(66, 71, 72));
        durataField.setForeground(new java.awt.Color(255, 255, 255));
        durataField.setBorder(null);

        jLabel6.setForeground(new java.awt.Color(66, 71, 72));
        jLabel6.setText("Data finalizare");

        dataFinalizareField.setBackground(new java.awt.Color(66, 71, 72));
        dataFinalizareField.setForeground(new java.awt.Color(255, 255, 255));
        dataFinalizareField.setBorder(null);

        ziActivitateField.setBackground(new java.awt.Color(66, 71, 72));
        ziActivitateField.setForeground(new java.awt.Color(255, 255, 255));
        ziActivitateField.setBorder(null);
        ziActivitateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ziActivitateFieldActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(66, 71, 72));
        jLabel7.setText("Ziua activitatii");

        jLabel8.setForeground(new java.awt.Color(66, 71, 72));
        jLabel8.setText("Numar maxim de participanti");

        partMaximField.setBackground(new java.awt.Color(66, 71, 72));
        partMaximField.setForeground(new java.awt.Color(255, 255, 255));
        partMaximField.setBorder(null);

        buttonInsertActGrupa.setBackground(new java.awt.Color(66, 71, 72));
        buttonInsertActGrupa.setForeground(new java.awt.Color(255, 255, 255));
        buttonInsertActGrupa.setText("Programare");

        buttonIntoarcereVizGrupa.setBackground(new java.awt.Color(66, 71, 72));
        buttonIntoarcereVizGrupa.setForeground(new java.awt.Color(255, 255, 255));
        buttonIntoarcereVizGrupa.setText("Inapoi");

        jLabel9.setForeground(new java.awt.Color(66, 71, 72));
        jLabel9.setText("Timp  expirare");

        timpExpiareField.setBackground(new java.awt.Color(66, 71, 72));
        timpExpiareField.setForeground(new java.awt.Color(255, 255, 255));
        timpExpiareField.setBorder(null);

        jLabel10.setForeground(new java.awt.Color(66, 71, 72));
        jLabel10.setText("(YYYY-MM-DD)");

        jLabel11.setForeground(new java.awt.Color(66, 71, 72));
        jLabel11.setText("(YYYY-MM-DD)");

        jLabel12.setForeground(new java.awt.Color(66, 71, 72));
        jLabel12.setText("(HH:MM:SS)");

        jLabel13.setForeground(new java.awt.Color(66, 71, 72));
        jLabel13.setText("(Nr. ore)");

        jLabel14.setForeground(new java.awt.Color(66, 71, 72));
        jLabel14.setText("(Nr. ore)");

        selectareProfComboBox.setBackground(new java.awt.Color(66, 71, 72));
        selectareProfComboBox.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setForeground(new java.awt.Color(66, 71, 72));
        jLabel15.setText("Solicitare profesor participant ");

        solicitProfCheckBox.setBackground(new java.awt.Color(255, 148, 96));
        solicitProfCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitProfCheckBoxActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(66, 71, 72));
        jLabel16.setText("Profesor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(errorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonInsertActGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonIntoarcereVizGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dataIncepereField)
                                            .addComponent(dataFinalizareField)
                                            .addComponent(ziActivitateField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9))
                                                    .addComponent(jLabel15))
                                                .addGap(11, 11, 11))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(solicitProfCheckBox)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(oraField)
                                                .addComponent(durataField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(partMaximField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(tipActivitateField)
                                                .addComponent(partMinimField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(timpExpiareField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(selectareProfComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dataIncepereField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataFinalizareField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ziActivitateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oraField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durataField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipActivitateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(partMinimField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(partMaximField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timpExpiareField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(solicitProfCheckBox))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectareProfComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIntoarcereVizGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInsertActGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ziActivitateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ziActivitateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ziActivitateFieldActionPerformed

    private void tipActivitateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipActivitateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipActivitateFieldActionPerformed

    private void solicitProfCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitProfCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solicitProfCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton buttonInsertActGrupa;
    public javax.swing.JButton buttonIntoarcereVizGrupa;
    public javax.swing.JTextField dataFinalizareField;
    public javax.swing.JTextField dataIncepereField;
    public javax.swing.JTextField durataField;
    public javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField oraField;
    public javax.swing.JTextField partMaximField;
    public javax.swing.JTextField partMinimField;
    public javax.swing.JComboBox<String> selectareProfComboBox;
    public javax.swing.JCheckBox solicitProfCheckBox;
    public javax.swing.JTextField timpExpiareField;
    public javax.swing.JTextField tipActivitateField;
    public javax.swing.JTextField ziActivitateField;
    // End of variables declaration//GEN-END:variables
}
