package UIPackage;
import java.awt.event.ActionListener;
import javax.swing.JTextField;


public class RegisterPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel(ActionListener registerButtonListener, ActionListener backButtonListener) {
        initComponents();
        registerButton.addActionListener(registerButtonListener);
        backButton.addActionListener(backButtonListener);
    }
    
    public javax.swing.JTextField[] getAllFields(){
        JTextField[] fieldArray = new JTextField[11];
        fieldArray[0] = cnpField;
        fieldArray[1] = emailField;
        fieldArray[2] = ibanField;
        fieldArray[3] = prenumeField;
        fieldArray[4] = passwordField;
        fieldArray[5] = numeField;
        fieldArray[6] = repeatPasswordField;
        fieldArray[7] = usernameField;
        fieldArray[8] = adresaField;
        fieldArray[9] = nrContractField;
        fieldArray[10] = nrTelefonField;
        return fieldArray;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleSelectRadioGroup = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        registerLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        ibanField = new javax.swing.JTextField();
        repeatPasswordField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeLabel = new javax.swing.JLabel();
        prenumeField = new javax.swing.JTextField();
        prenumeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        cnpField = new javax.swing.JTextField();
        cnpLabel = new javax.swing.JLabel();
        ibanLabel = new javax.swing.JLabel();
        numeField = new javax.swing.JTextField();
        profesorRadioButton = new javax.swing.JRadioButton();
        studentRadioButton = new javax.swing.JRadioButton();
        administratorRadioButton = new javax.swing.JRadioButton();
        anStudiuLabel = new javax.swing.JLabel();
        anStudiuComboBox = new javax.swing.JComboBox<>();
        departamentLabel = new javax.swing.JLabel();
        departamentTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        adresaLabel = new javax.swing.JLabel();
        adresaField = new javax.swing.JTextField();
        nrContractLabel = new javax.swing.JLabel();
        nrContractField = new javax.swing.JTextField();
        nrTelefonLabel = new javax.swing.JLabel();
        nrTelefonField = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(255, 148, 96));
        setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        setMaximumSize(new java.awt.Dimension(522, 690));

        registerLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(66, 71, 72));
        registerLabel.setText("Register");

        usernameField.setBackground(new java.awt.Color(66, 71, 72));
        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.setBorder(null);

        passwordField.setBackground(new java.awt.Color(66, 71, 72));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(null);

        ibanField.setBackground(new java.awt.Color(66, 71, 72));
        ibanField.setForeground(new java.awt.Color(255, 255, 255));
        ibanField.setBorder(null);

        repeatPasswordField.setBackground(new java.awt.Color(66, 71, 72));
        repeatPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        repeatPasswordField.setText("  Repeta parola");
        repeatPasswordField.setBorder(null);
        repeatPasswordField.setPreferredSize(new java.awt.Dimension(15, 24));

        usernameLabel.setForeground(new java.awt.Color(66, 71, 72));
        usernameLabel.setText("Username");

        jLabel3.setForeground(new java.awt.Color(66, 71, 72));
        jLabel3.setText("Parola");

        numeLabel.setForeground(new java.awt.Color(66, 71, 72));
        numeLabel.setText("Nume");

        prenumeField.setBackground(new java.awt.Color(66, 71, 72));
        prenumeField.setForeground(new java.awt.Color(255, 255, 255));
        prenumeField.setBorder(null);

        prenumeLabel.setForeground(new java.awt.Color(66, 71, 72));
        prenumeLabel.setText("Prenume");

        emailLabel.setForeground(new java.awt.Color(66, 71, 72));
        emailLabel.setText("Email");

        emailField.setBackground(new java.awt.Color(66, 71, 72));
        emailField.setForeground(new java.awt.Color(255, 255, 255));
        emailField.setBorder(null);

        cnpField.setBackground(new java.awt.Color(66, 71, 72));
        cnpField.setForeground(new java.awt.Color(255, 255, 255));
        cnpField.setBorder(null);

        cnpLabel.setForeground(new java.awt.Color(66, 71, 72));
        cnpLabel.setText("CNP");

        ibanLabel.setForeground(new java.awt.Color(66, 71, 72));
        ibanLabel.setText("IBAN");

        numeField.setBackground(new java.awt.Color(66, 71, 72));
        numeField.setForeground(new java.awt.Color(255, 255, 255));
        numeField.setBorder(null);

        profesorRadioButton.setBackground(new java.awt.Color(255, 148, 96));
        roleSelectRadioGroup.add(profesorRadioButton);
        profesorRadioButton.setForeground(new java.awt.Color(66, 71, 72));
        profesorRadioButton.setText("Profesor");
        profesorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesorRadioButtonActionPerformed(evt);
            }
        });

        studentRadioButton.setBackground(new java.awt.Color(255, 148, 96));
        roleSelectRadioGroup.add(studentRadioButton);
        studentRadioButton.setForeground(new java.awt.Color(66, 71, 72));
        studentRadioButton.setText("Student");
        studentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRadioButtonActionPerformed(evt);
            }
        });

        administratorRadioButton.setBackground(new java.awt.Color(255, 148, 96));
        roleSelectRadioGroup.add(administratorRadioButton);
        administratorRadioButton.setForeground(new java.awt.Color(66, 71, 72));
        administratorRadioButton.setText("Administrator");
        administratorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administratorRadioButtonActionPerformed(evt);
            }
        });

        anStudiuLabel.setForeground(new java.awt.Color(255, 255, 255));
        anStudiuLabel.setText("An studiu:");
        anStudiuLabel.setEnabled(false);

        anStudiuComboBox.setForeground(new java.awt.Color(255, 255, 255));
        anStudiuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV" }));
        anStudiuComboBox.setEnabled(false);

        departamentLabel.setForeground(new java.awt.Color(255, 255, 255));
        departamentLabel.setText("Departament");
        departamentLabel.setEnabled(false);

        departamentTextField.setBackground(new java.awt.Color(66, 71, 72));
        departamentTextField.setForeground(new java.awt.Color(255, 255, 255));
        departamentTextField.setEnabled(false);

        backButton.setBackground(new java.awt.Color(66, 71, 72));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Inapoi");

        registerButton.setBackground(new java.awt.Color(66, 71, 72));
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Inregistrare");

        errorLabel.setForeground(new java.awt.Color(255, 255, 255));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        adresaLabel.setForeground(new java.awt.Color(66, 71, 72));
        adresaLabel.setText("Adresa");

        adresaField.setBackground(new java.awt.Color(66, 71, 72));
        adresaField.setForeground(new java.awt.Color(255, 255, 255));
        adresaField.setBorder(null);

        nrContractLabel.setForeground(new java.awt.Color(66, 71, 72));
        nrContractLabel.setText("Numar de contract");

        nrContractField.setBackground(new java.awt.Color(66, 71, 72));
        nrContractField.setForeground(new java.awt.Color(255, 255, 255));
        nrContractField.setBorder(null);

        nrTelefonLabel.setForeground(new java.awt.Color(66, 71, 72));
        nrTelefonLabel.setText("Nr. telefon");

        nrTelefonField.setBackground(new java.awt.Color(66, 71, 72));
        nrTelefonField.setForeground(new java.awt.Color(255, 255, 255));
        nrTelefonField.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nrTelefonLabel)
                            .addComponent(prenumeLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel)
                                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailLabel)
                                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cnpLabel)
                                        .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nrTelefonField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(prenumeField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(nrContractField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(profesorRadioButton)
                                    .addComponent(anStudiuLabel)
                                    .addComponent(anStudiuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departamentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departamentLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(studentRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(administratorRadioButton)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ibanField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibanLabel)
                            .addComponent(numeLabel)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adresaLabel)
                                    .addComponent(cnpField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(numeField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nrContractLabel)
                                    .addComponent(adresaField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(51, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerLabel)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cnpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeLabel)
                    .addComponent(adresaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenumeLabel)
                    .addComponent(nrContractLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenumeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrContractField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrTelefonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrTelefonField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ibanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ibanField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesorRadioButton)
                    .addComponent(studentRadioButton)
                    .addComponent(administratorRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anStudiuLabel)
                    .addComponent(departamentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anStudiuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(errorLabel)
                .addGap(36, 36, 36)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profesorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesorRadioButtonActionPerformed
        if(profesorRadioButton.isSelected()){
            departamentLabel.setEnabled(true);
            departamentTextField.setEnabled(true);
            anStudiuLabel.setEnabled(false);
            anStudiuComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_profesorRadioButtonActionPerformed

    private void studentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRadioButtonActionPerformed
        if(studentRadioButton.isSelected()){
            departamentLabel.setEnabled(false);
            departamentTextField.setEnabled(false);
            anStudiuLabel.setEnabled(true);
            anStudiuComboBox.setEnabled(true);
        }
    }//GEN-LAST:event_studentRadioButtonActionPerformed

    private void administratorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administratorRadioButtonActionPerformed
        if(administratorRadioButton.isSelected()){
            departamentLabel.setEnabled(false);
            departamentTextField.setEnabled(false);
            anStudiuLabel.setEnabled(false);
            anStudiuComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_administratorRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton administratorRadioButton;
    public javax.swing.JTextField adresaField;
    private javax.swing.JLabel adresaLabel;
    public javax.swing.JComboBox<String> anStudiuComboBox;
    private javax.swing.JLabel anStudiuLabel;
    public javax.swing.JButton backButton;
    public javax.swing.JTextField cnpField;
    private javax.swing.JLabel cnpLabel;
    private javax.swing.JLabel departamentLabel;
    public javax.swing.JTextField departamentTextField;
    public javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    public javax.swing.JLabel errorLabel;
    public javax.swing.JTextField ibanField;
    private javax.swing.JLabel ibanLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField nrContractField;
    private javax.swing.JLabel nrContractLabel;
    public javax.swing.JTextField nrTelefonField;
    private javax.swing.JLabel nrTelefonLabel;
    public javax.swing.JTextField numeField;
    private javax.swing.JLabel numeLabel;
    public javax.swing.JTextField passwordField;
    public javax.swing.JTextField prenumeField;
    private javax.swing.JLabel prenumeLabel;
    public javax.swing.JRadioButton profesorRadioButton;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;
    public javax.swing.JTextField repeatPasswordField;
    private javax.swing.ButtonGroup roleSelectRadioGroup;
    public javax.swing.JRadioButton studentRadioButton;
    public javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
