package UIPackage;

import java.awt.event.ActionListener;

public class VizDateProfesorPanel extends javax.swing.JPanel {

    /**
     * Creates new form VizDateProfesor
     */
    public VizDateProfesorPanel(ActionListener backToHomePanelListener) {
        initComponents();
        buttonReturn.addActionListener(backToHomePanelListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adresaField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numeField = new javax.swing.JTextField();
        nrtelefonField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        prenumeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        nrcontractField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        departamentField = new javax.swing.JTextField();
        cnpField = new javax.swing.JTextField();
        nrOreMinField = new javax.swing.JTextField();
        buttonReturn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        nrOreMaxField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 148, 96));

        jLabel5.setForeground(new java.awt.Color(66, 71, 72));
        jLabel5.setText("Adresa");

        jLabel10.setForeground(new java.awt.Color(66, 71, 72));
        jLabel10.setText("Nr. ore minim");

        adresaField.setBackground(new java.awt.Color(66, 71, 72));
        adresaField.setForeground(new java.awt.Color(255, 255, 255));
        adresaField.setBorder(null);
        adresaField.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(66, 71, 72));
        jLabel1.setText("Nume");

        jLabel6.setForeground(new java.awt.Color(66, 71, 72));
        jLabel6.setText("Email");

        numeField.setBackground(new java.awt.Color(66, 71, 72));
        numeField.setForeground(new java.awt.Color(255, 255, 255));
        numeField.setBorder(null);
        numeField.setEnabled(false);
        numeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeFieldActionPerformed(evt);
            }
        });

        nrtelefonField.setBackground(new java.awt.Color(66, 71, 72));
        nrtelefonField.setForeground(new java.awt.Color(255, 255, 255));
        nrtelefonField.setBorder(null);
        nrtelefonField.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(66, 71, 72));
        jLabel2.setText("Username");

        emailField.setBackground(new java.awt.Color(66, 71, 72));
        emailField.setForeground(new java.awt.Color(255, 255, 255));
        emailField.setBorder(null);
        emailField.setEnabled(false);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        prenumeField.setBackground(new java.awt.Color(66, 71, 72));
        prenumeField.setForeground(new java.awt.Color(255, 255, 255));
        prenumeField.setBorder(null);
        prenumeField.setEnabled(false);

        jLabel7.setForeground(new java.awt.Color(66, 71, 72));
        jLabel7.setText("Nr. Contract");

        jLabel8.setForeground(new java.awt.Color(66, 71, 72));
        jLabel8.setText("Nr. Telefon");

        usernameField.setBackground(new java.awt.Color(66, 71, 72));
        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.setBorder(null);
        usernameField.setEnabled(false);

        nrcontractField.setBackground(new java.awt.Color(66, 71, 72));
        nrcontractField.setForeground(new java.awt.Color(255, 255, 255));
        nrcontractField.setBorder(null);
        nrcontractField.setEnabled(false);
        nrcontractField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrcontractFieldActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(66, 71, 72));
        jLabel3.setText("CNP");

        jLabel9.setForeground(new java.awt.Color(66, 71, 72));
        jLabel9.setText("Departament");

        jLabel4.setForeground(new java.awt.Color(66, 71, 72));
        jLabel4.setText("Prenume");

        departamentField.setBackground(new java.awt.Color(66, 71, 72));
        departamentField.setForeground(new java.awt.Color(255, 255, 255));
        departamentField.setBorder(null);
        departamentField.setEnabled(false);

        cnpField.setBackground(new java.awt.Color(66, 71, 72));
        cnpField.setForeground(new java.awt.Color(255, 255, 255));
        cnpField.setBorder(null);
        cnpField.setEnabled(false);

        nrOreMinField.setBackground(new java.awt.Color(66, 71, 72));
        nrOreMinField.setForeground(new java.awt.Color(255, 255, 255));
        nrOreMinField.setBorder(null);
        nrOreMinField.setEnabled(false);

        buttonReturn.setBackground(new java.awt.Color(66, 71, 72));
        buttonReturn.setForeground(new java.awt.Color(255, 255, 255));
        buttonReturn.setText("Intoarcere ");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(66, 71, 72));
        jLabel11.setText("Nr. ore maxim");

        nrOreMaxField.setBackground(new java.awt.Color(66, 71, 72));
        nrOreMaxField.setForeground(new java.awt.Color(255, 255, 255));
        nrOreMaxField.setBorder(null);
        nrOreMaxField.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(66, 71, 72));
        jLabel12.setText("Date personale");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(prenumeField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(numeField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cnpField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(adresaField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailField)
                                    .addComponent(nrtelefonField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nrcontractField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nrOreMinField)
                                    .addComponent(departamentField, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(nrOreMaxField))))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(prenumeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cnpField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adresaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrtelefonField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nrcontractField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(departamentField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrOreMinField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrOreMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(buttonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void nrcontractFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrcontractFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrcontractFieldActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField adresaField;
    private javax.swing.JButton buttonReturn;
    public javax.swing.JTextField cnpField;
    public javax.swing.JTextField departamentField;
    public javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField nrOreMaxField;
    public javax.swing.JTextField nrOreMinField;
    public javax.swing.JTextField nrcontractField;
    public javax.swing.JTextField nrtelefonField;
    public javax.swing.JTextField numeField;
    public javax.swing.JTextField prenumeField;
    public javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
