/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package BDProjectv7;

import BDProjectv7.BDConnection;
import BDProjectv7.ViewController;



public class App {

    public static void main(String[] args) {
        BDConnection bdconn = new BDConnection();
        ViewController controller = new ViewController(bdconn);
    }
}
